os: linux
language: node_js
node_js:
    - 10
    - 12
    - 14
    - node
install:
    - yarn
script:
    - npm run lint
    - npm run test
    - npm run build
cache:
    directories:
        - node_modules
